"""init trabalhador

Revision ID: 09ec8fc85d11
Revises: 
Create Date: 2026-02-13 23:32:15.690792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ec8fc85d11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabalhador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('profissao', sa.String(length=80), nullable=False),
    sa.Column('whatsapp', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabalhador')
    # ### end Alembic commands ###
